version: '3.8'

services:
  orquestador:
    build: .
    ports:
      - "5005:5005"
    depends_on:
      - db
      - ms_pagos
      - ms_inventario
      - ms_catalogo
      - ms_compras
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5005
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:12345678@db/orquestador
      - INVENTORY_SERVICE_URL=http://ms_inventario:5000/inventario
      - CATALOG_SERVICE_URL=http://ms_catalogo:5001/catalogo
      - PURCHASE_SERVICE_URL=http://ms_compras:5002/compras
      - PAYMENT_SERVICE_URL=http://ms_pagos:5003/pagos

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: orquestador
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ms_pagos:
    build:
      context: C:/Users/juanv/OneDrive/Documentos/ms-pagos
    ports:
      - "5003:5003"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5003

  ms_inventario:
    build:
      context: C:/Users/juanv/OneDrive/Documentos/ms-inventario
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000

  ms_catalogo:
    build:
      context: C:/Users/juanv/OneDrive/Documentos/ms-catalogo
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001

  ms_compras:
    build:
      context: C:/Users/juanv/Downloads/ms-compras
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5002

volumes:
  postgres_data: