version: '3.8'

networks:
  orquestador_network:

services:
  orquestador:
    ports:
      - "5005:5005"
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orquestador.rule=Host(`orquestador.localhost`)"
      - "traefik.http.routers.orquestador.entrypoints=web"
      - "traefik.http.services.orquestador.loadbalancer.server.port=5005"
    depends_on:
      - db
      - ms_pagos
      - ms_inventario
      - ms_catalogo
      - ms_compras
      - rabbitmq
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5005
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:12345678@db/orquestador
      - INVENTORY_SERVICE_URL=http://ms_inventario:5000/inventario
      - CATALOG_SERVICE_URL=http://ms_catalogo:5001/catalogo
      - PURCHASE_SERVICE_URL=http://ms_compras:5002/compras
      - PAYMENT_SERVICE_URL=http://ms_pagos:5003/pagos
    networks:
      - orquestador_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: orquestador
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orquestador_network

  ms_pagos:
    ports:
      - "5003:5003"
    build:
      context: C:/Users/juanv/OneDrive/Documentos/ms-pagos
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms_pagos.rule=Host(`ms_pagos.localhost`)"
      - "traefik.http.routers.ms_pagos.entrypoints=web"
      - "traefik.http.services.ms_pagos.loadbalancer.server.port=5003"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5003
    networks:
      - orquestador_network

  ms_inventario:
    ports:
      - "5000:5000"
    build:
      context: C:/Users/juanv/OneDrive/Documentos/ms-inventario
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms_inventario.rule=Host(`ms_inventario.localhost`)"
      - "traefik.http.routers.ms_inventario.entrypoints=web"
      - "traefik.http.services.ms_inventario.loadbalancer.server.port=5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    networks:
      - orquestador_network

  ms_catalogo:
    ports:
      - "5001:5001"
    build:
      context: C:/Users/juanv/OneDrive/Documentos/ms-catalogo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms_catalogo.rule=Host(`ms_catalogo.localhost`)"
      - "traefik.http.routers.ms_catalogo.entrypoints=web"
      - "traefik.http.services.ms_catalogo.loadbalancer.server.port=5001"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001
    networks:
      - orquestador_network

  ms_compras:
    ports:
      - "5002:5002"
    build:
      context: C:/Users/juanv/Downloads/ms-compras
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms_compras.rule=Host(`ms_compras.localhost`)"
      - "traefik.http.routers.ms_compras.entrypoints=web"
      - "traefik.http.services.ms_compras.loadbalancer.server.port=5002"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5002
    networks:
      - orquestador_network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - orquestador_network

  traefik:
    image: "traefik:v2.5"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"      # Antes era "81:80", ahora está corregido
      - "8081:8080"  # Panel de Traefik en localhost:8081
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - orquestador_network

volumes:
  postgres_data:
